# Generated by Django 2.2.4 on 2019-10-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('discription', models.CharField(max_length=400, null=True)),
                ('start', models.CharField(max_length=30, null=True)),
                ('end', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
